Update munki_rebrand.py
Added error when icon file is declared but cannot be found, without this we hit an issue later on:

```
Traceback (most recent call last):
  File "/Users/ben/Downloads/munki-rebrand-main/munki_rebrand.py", line 649, in <module>
    main()
  File "/Users/ben/Downloads/munki-rebrand-main/munki_rebrand.py", line 574, in main
    if icns:
UnboundLocalError: local variable 'icns' referenced before assignment
```